from pathlib import Path
p=Path('main.go')
s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing {label}')
    s=s.replace(old,new,1)

rep('const hostBuild = "34.4-child-hwnd"','const hostBuild = "34.5-zorder-top"','hostBuild')
rep('    procDestroyWindow      = user32.NewProc("DestroyWindow")\n', '    procDestroyWindow      = user32.NewProc("DestroyWindow")\n    procGetWindow           = user32.NewProc("GetWindow")\n    procGetWindowRect       = user32.NewProc("GetWindowRect")\n', 'procs')
rep('    swpNoZOrder = 0x0004\n    swpNoActivate = 0x0010\n', '    swpNoSize = 0x0001\n    swpNoMove = 0x0002\n    swpNoActivate = 0x0010\n    swpShowWindow = 0x0040\n', 'swp constants')
rep('    wsClipChildren = 0x02000000\n)', '    wsClipChildren = 0x02000000\n    gwHwndNext = 2\n    gwHwndPrev = 3\n)', 'gw constants')
rep('    NavigationCount int    `json:"navigationCount"`\n}', '    NavigationCount int    `json:"navigationCount"`\n    NativeVisible   bool   `json:"nativeVisible"`\n    WindowRect      string `json:"windowRect"`\n    ZPrevHWND       string `json:"zPrevHwnd"`\n    ZNextHWND       string `json:"zNextHwnd"`\n}', 'state fields')
rep('func waitForWindow(pid uint32,timeout time.Duration) uintptr { deadline:=time.Now().Add(timeout); for time.Now().Before(deadline){ if hwnd:=findWindowByPID(pid); hwnd!=0{return hwnd}; time.Sleep(120*time.Millisecond) }; return 0 }\n', '''func waitForWindow(pid uint32,timeout time.Duration) uintptr { deadline:=time.Now().Add(timeout); for time.Now().Before(deadline){ if hwnd:=findWindowByPID(pid); hwnd!=0{return hwnd}; time.Sleep(120*time.Millisecond) }; return 0 }\n\ntype nativeRect struct { Left, Top, Right, Bottom int32 }\nfunc hwndText(hwnd uintptr) string { if hwnd==0{return ""}; return fmt.Sprintf("0x%X",hwnd) }\nfunc (c *controller) refreshNativeDiagnostics(){\n    if c.hwnd==0{return}\n    vis,_,_:=procIsWindowVisible.Call(c.hwnd)\n    var rc nativeRect\n    ok,_,_:=procGetWindowRect.Call(c.hwnd,uintptr(unsafe.Pointer(&rc)))\n    prev,_,_:=procGetWindow.Call(c.hwnd,gwHwndPrev)\n    next,_,_:=procGetWindow.Call(c.hwnd,gwHwndNext)\n    rect:=""\n    if ok!=0 { rect=fmt.Sprintf("x=%d y=%d w=%d h=%d",rc.Left,rc.Top,rc.Right-rc.Left,rc.Bottom-rc.Top) }\n    c.mutate(func(s *hostState){s.NativeVisible=vis!=0;s.WindowRect=rect;s.ZPrevHWND=hwndText(prev);s.ZNextHWND=hwndText(next)})\n}\nfunc (c *controller) forceTop(){\n    if c.hwnd==0{return}\n    _,_,_=procSetWindowPos.Call(c.hwnd,0,0,0,0,0,swpNoMove|swpNoSize|swpNoActivate|swpShowWindow)\n    if c.w!=nil { c.w.Resize() }\n    _,_,_=procRedrawWindow.Call(c.hwnd,0,0,rdwInvalidate|rdwAllChildren|rdwUpdateNow)\n    _,_,_=procUpdateWindow.Call(c.hwnd)\n}\n''', 'diagnostics funcs')
rep('    _,_,_=procSetWindowPos.Call(c.hwnd,0,uintptr(x),uintptr(y),uintptr(width),uintptr(height),swpNoZOrder|swpNoActivate)\n', '    _,_,_=procSetWindowPos.Call(c.hwnd,0,uintptr(x),uintptr(y),uintptr(width),uintptr(height),swpNoActivate|swpShowWindow)\n', 'move top')
rep('    if show { _,_,_=procShowWindow.Call(c.hwnd,swShow); _,_,_=procSetFocus.Call(c.hwnd) }\n', '    if show { _,_,_=procShowWindow.Call(c.hwnd,swShow); c.forceTop(); _,_,_=procSetFocus.Call(c.hwnd) }\n', 'show top')
rep('    mux.HandleFunc("/health",cors(func(w http.ResponseWriter,r *http.Request){jsonWrite(w,200,c.snapshot())}))\n    mux.HandleFunc("/state",cors(func(w http.ResponseWriter,r *http.Request){jsonWrite(w,200,c.snapshot())}))\n', '    mux.HandleFunc("/health",cors(func(w http.ResponseWriter,r *http.Request){c.refreshNativeDiagnostics();jsonWrite(w,200,c.snapshot())}))\n    mux.HandleFunc("/state",cors(func(w http.ResponseWriter,r *http.Request){c.refreshNativeDiagnostics();jsonWrite(w,200,c.snapshot())}))\n', 'dynamic diagnostics')
rep('    c:=&controller{log:logger};c.state=hostState{Marker:marker,HostBuild:hostBuild,WindowMode:"explicit-static-child-hwnd",HostPID:os.Getpid(),ParentPID:*parentPID,Port:*port}\n', '    c:=&controller{log:logger};c.state=hostState{Marker:marker,HostBuild:hostBuild,WindowMode:"explicit-static-child-hwnd-zorder-top",HostPID:os.Getpid(),ParentPID:*parentPID,Port:*port}\n', 'window mode')
rep('    go func(){ticker:=time.NewTicker(time.Second);defer ticker.Stop();for range ticker.C{ok,_,_:=procIsWindow.Call(parent);if ok==0{logger.Printf("parent window disappeared; terminating");w.Terminate();return}}}()\n', '''    go func(){ticker:=time.NewTicker(time.Second);defer ticker.Stop();for range ticker.C{ok,_,_:=procIsWindow.Call(parent);if ok==0{logger.Printf("parent window disappeared; terminating");w.Terminate();return}}}()\n    go func(){\n        ticker:=time.NewTicker(400*time.Millisecond);defer ticker.Stop()\n        for range ticker.C {\n            if !c.snapshot().Visible { continue }\n            _=c.runUI(2*time.Second,func() error{c.forceTop();return nil})\n        }\n    }()\n''', 'zorder ticker')
p.write_text(s,encoding='utf-8')
print('patched V34.5', len(s))
